name: "Catalyst Stats Processor"
description: "Trigger Netlify background function and save results"
inputs:
  project_ids:
    description: "Comma-separated project IDs"
    required: true
  output_file:
    description: "Path to output file"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
